backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to main)
media_folder: public/media
collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/home.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Accent", name: "accent", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Bio"
        name: "bio"
        file: "content/bio.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Accent", name: "accent", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Experience"
        name: "experience"
        file: "content/experience.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Accent", name: "accent", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Contact"
        name: "Contact"
        file: "content/contact.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Accent", name: "accent", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
