backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to main)
media_folder: public/media
collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/home.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Accent", name: "accent", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "About"
        name: "about"
        file: "content/about.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Accent", name: "accent", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Work"
        name: "work"
        file: "content/work.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Accent", name: "accent", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Contact"
        name: "Contact"
        file: "content/contact.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Accent", name: "accent", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
